language: ruby

install:
  - gem install bundler
  - bundler install --jobs=3 --retry=3 --without document development

rvm:
  - 2.0
  - 2.1
  - 2.2
  - 2.3.1
  - jruby
  - rbx-2

matrix:
  allow_failures:
    - rvm: rbx-2
    - rvm: jruby